<?php

namespace Tests;

use App\Exceptions\Handler;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Contracts\Container\Container;
use Illuminate\Contracts\Debug\ExceptionHandler;
use Throwable;

trait CreatesApplication
{
    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        return $app;
    }


    //on je stavio u TestCase ovu metodu. i ona zajebava
    protected function disableExceptionHandling(){
        $this->app->instance(ExceptionHandler::class,new class extends Handler{
            public function __construct()
            {
                //parent::__construct($container);
            }

            public function report(Throwable $e)
            {
                return parent::report($e); // TODO: Change the autogenerated stub
            }

            public function render($request, Throwable $e)
            {
                //možda će trebati ovo ili ovo throw e
                //return parent::render($request, $e); // TODO: Change the autogenerated stub
                throw $e;
            }
        });
    }
}
