<?php

namespace Tests\Feature;

use App\Billing\PaymentGateway;
use App\Models\Concert;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use App\Billing\FakePaymentGateway;


class PurchaseTicketsTest extends TestCase
{
    use DatabaseMigrations;
    public $payment_gateway;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->payment_gateway=new FakePaymentGateway;
        //ne znam šta ovo znači.negde na početku drugog odeljka
        $this->app->instance(PaymentGateway::class, $this->payment_gateway);
    }

    private function orderTickets($concert, $params){
        $this->json('POST', "/concerts/{$concert->id}/orders", $params);
    }

    private function customAssertValidationError($field){
        $this->assertResponseStatus(422);
        //umesto this decodeResponseJson()
        //dd($this->response->assertJsonValidationErrors('email'));
        //$this->assertArrayHasKey('email', $this->decodeResponseJson()); - zastarelo, treba ovo dole
        $this->response->assertJsonValidationErrors($field);
    }

    public function test_customer_can_purchase_published_concert_ticket()
    {
        $this->disableExceptionHandling();
        $concert=Concert::factory()->published()->create(['ticket_price'=>3250]);

        $this->orderTickets($concert, [
            'email'=>'john@gmail.com',
            'ticket_quantity'=>3,
            'payment_token'=>$this->payment_gateway->getValidToken()
        ]);

        $this->assertResponseStatus(201);
        //znači da je naplaćeno kupcu
        $this->assertEquals(9750, $this->payment_gateway->totalCharges());

        $order=$concert->orders()->where('email', 'john@gmail.com')->first();
        $this->assertNotNull($order);
        $this->assertEquals('3', $order->tickets->count());

    }

    public function test_cannot_purchase_tickets_to_unpublished_concert(){

        //dole skidamo komentar ako želimo da vidimo koji je exception (bio je model not foun)
        //a pošto želimo da laravel prebaci u 404, ne treba disableExceptionHandling

        $concert=Concert::factory()->unpublished()->create();

        $this->orderTickets($concert, [
            'email'=>'john@gmail.com',
            'ticket_quantity'=>3,
            'payment_token'=>$this->payment_gateway->getValidToken()
        ]);

        $this->assertResponseStatus(404);
        //u bazi nemamo nijedan red sa orderima (jer je uvek refresh db)
        $this->assertEquals(0, $concert->orders()->count());

        //znači da nije naplaćeno kupcu
        $this->assertEquals(0, $this->payment_gateway->totalCharges());

    }

    public function test_email_is_required_to_purchase_tickets(){
        //$this->disableExceptionHandling();

        $concert=Concert::factory()->published()->create();

        $this->orderTickets($concert, [
            'ticket_quantity'=>3,
            'payment_token'=>$this->payment_gateway->getValidToken()
        ]);

        $this->customAssertValidationError('email');


    }

    public function test_email_must_be_valid_to_purchase_tickets(){
        $concert=Concert::factory()->published()->create();

        $this->orderTickets($concert, [
            'email'=>'nije mail',
            'ticket_quantity'=>3,
            'payment_token'=>$this->payment_gateway->getValidToken()
        ]);

        $this->customAssertValidationError('email');
    }

    public function test_ticket_quantity_is_required_to_purchase_tickets(){
        $concert=Concert::factory()->published()->create();

        $this->orderTickets($concert, [
            'email'=>'nije mail',
            'payment_token'=>$this->payment_gateway->getValidToken()
        ]);

        $this->customAssertValidationError('ticket_quantity');
    }

    public function test_ticket_quantity_must_be_at_least_one_to_purchase_tickets(){
        $concert=Concert::factory()->published()->create();

        $this->orderTickets($concert, [
            'email'=>'jeste@email.com',
            'ticket_quantity'=>0,
            'payment_token'=>$this->payment_gateway->getValidToken()
        ]);

        $this->customAssertValidationError('ticket_quantity');
    }

    public function test_payment_token_is_required_to_purchase_tickets(){
        $concert=Concert::factory()->published()->create();

        $this->orderTickets($concert, [
            'email'=>'jeste@email.com',
            'ticket_quantity'=>3,
        ]);

        $this->customAssertValidationError('payment_token');
    }

    public function test_order_is_not_created_if_payment_fails(){

        //kad javi da očekujemo 422 a lara da 500 onda moramo da enejblujemo ovo ispod
        //sprečavamo laravel da konvertuje exception u http response
        $this->disableExceptionHandling();

        $concert=Concert::factory()->published()->create(['ticket_price'=>3250]);

        $this->orderTickets($concert, [
            'email'=>'john@gmail.com',
            'ticket_quantity'=>3,
            'payment_token'=>'invalid-token'
        ]);

        $this->assertResponseStatus(422);
        $order=$concert->orders()->where('email', 'john@gmail.com')->first();
        $this->assertNull($order);
    }


}
